kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: files-uploads
  annotations:
    description: Defines the PVC associated to files service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
