kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: events-database
  annotations:
    description: Defines the PVC associated to MongoDB
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi