kind: Service
apiVersion: v1
metadata:
  name: events-database
  annotations:
    description: Exposes the database server
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: events-database